[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps =
    madhephaestus/ESP32Servo
    
monitor_speed = 115200
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D IR_DEBUG=1
    -D HTTP_DEBUG=0
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
monitor_dtr = 0
monitor_rts = 0